// Mock product catalog for the Voga Closet dummy site.
//
// IMPORTANT: Many of these products carry real names, prices, and images
// pulled from vogacloset.com/saudi/ar/ on 2026-05-18. The Karen Millen
// products are real (Use Case 7 — Brand Campaign). Men/Women products are
// real. Kids/Beauty/Home products fall back to gradient placeholders for
// now since we didn't extract those PLPs this session.
//
// Each product carries `collection` and `vendor` fields so the order payload
// works for Gameball use cases 6 (category) and 7 (brand) without refactoring.

export type Product = {
  id: string;
  slug: string;
  nameAr: string;
  nameEn: string;
  price: number;
  originalPrice?: number;
  category: "women" | "men" | "kids" | "beauty" | "home";
  brand: string;
  brandAr: string;
  brandSlug: string;
  sizes: string[];
  colors: { name: string; hex: string }[];
  // Image strategy: prefer real Voga product image if available; otherwise
  // fall back to gradient + emoji placeholder.
  image?: string;          // path under /public, e.g. "/voga/products/karen-millen-stretch-midi.webp"
  emoji?: string;
  bgGradient?: string;
  rating: number;
  reviewCount: number;
  description: string;
};

export const PRODUCTS: Product[] = [
  // ───── KAREN MILLEN (3 — real images, real names from vogacloset.com) ─────
  {
    id: "km-001",
    slug: "karen-millen-stretch-midi",
    nameAr: "فستان ميدي إستريتش",
    nameEn: "Karen Millen Compact Stretch Midi Dress",
    price: 706,
    originalPrice: 2031,
    category: "women",
    brand: "Karen Millen",
    brandAr: "كارين ميلين",
    brandSlug: "karen-millen",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "أسود", hex: "#000000" }, { name: "كحلي", hex: "#1a1a4e" }],
    image: "/voga/products/karen-millen-stretch-midi.webp",
    rating: 4.8,
    reviewCount: 142,
    description: "فستان ميدي بقماش إستريتش مفصّل بقصة كلاسيكية. أنيق للمناسبات الراقية.",
  },
  {
    id: "km-002",
    slug: "karen-millen-halter-midi",
    nameAr: "فستان ميدي إستريتش بياقة هالتر",
    nameEn: "Karen Millen Halter Neck Midi Dress",
    price: 587,
    originalPrice: 1946,
    category: "women",
    brand: "Karen Millen",
    brandAr: "كارين ميلين",
    brandSlug: "karen-millen",
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "أحمر", hex: "#a01818" }],
    image: "/voga/products/karen-millen-halter-midi.webp",
    rating: 4.7,
    reviewCount: 89,
    description: "فستان ميدي بياقة هالتر وقصّة بلوك لوني. مثالي للمناسبات الصيفية.",
  },
  {
    id: "km-003",
    slug: "karen-millen-pointelle-knit",
    nameAr: "فستان ميدي بونتيل بشرائح شفافة",
    nameEn: "Karen Millen Pointelle Stitch Knit Midi Dress",
    price: 357,
    originalPrice: 1182,
    category: "women",
    brand: "Karen Millen",
    brandAr: "كارين ميلين",
    brandSlug: "karen-millen",
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "كريمي", hex: "#f5f0e1" }],
    image: "/voga/products/karen-millen-pointelle.webp",
    rating: 4.6,
    reviewCount: 67,
    description: "فستان ميدي بنسج البونتيل مع شرائح شفافة. خفيف وأنيق.",
  },

  // ───── WOMEN — other brands (7 — real images, real names) ─────
  {
    id: "wm-001",
    slug: "principles-jacquard-midi",
    nameAr: "فستان ميدي جاكار بخصر منسدل بحافة واسعة",
    nameEn: "Principles by Debenhams Jacquard Midi Dress",
    price: 236,
    originalPrice: 428,
    category: "women",
    brand: "Principles by Debenhams",
    brandAr: "برينسيبلز باي دبنهامز",
    brandSlug: "principles",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "أزرق", hex: "#1a3a5f" }],
    image: "/voga/products/principles-jacquard-midi.webp",
    rating: 4.4,
    reviewCount: 78,
    description: "فستان ميدي بنسيج جاكار وخصر منسدل وحافة واسعة. تصميم عصري ومريح.",
  },
  {
    id: "wm-002",
    slug: "coast-lace-pleat",
    nameAr: "فستان بكسرات بتوب دانتيل بأزرار محجرة",
    nameEn: "Coast Fashion Lace Top Pleat Skirt Dress",
    price: 570,
    originalPrice: 1267,
    category: "women",
    brand: "Coast Fashion",
    brandAr: "كوست فاشن",
    brandSlug: "coast-fashion",
    sizes: ["S", "M", "L"],
    colors: [{ name: "أسود", hex: "#000" }],
    image: "/voga/products/coast-lace-pleat.webp",
    rating: 4.6,
    reviewCount: 53,
    description: "فستان بتوب دانتيل وتنورة بكسرات. الأزرار المحجرة تضيف لمسة من الفخامة.",
  },
  {
    id: "wm-003",
    slug: "clubl-sequin-midi",
    nameAr: "فستان ميدي بتصميم بشكل A بياقة مربعة مزين بالترتر",
    nameEn: "Club L London Sequin A-Line Midi Dress",
    price: 496,
    originalPrice: 1529,
    category: "women",
    brand: "Club L London",
    brandAr: "كلوب ال لندن",
    brandSlug: "club-l-london",
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "ذهبي", hex: "#d4af37" }],
    image: "/voga/products/clubl-sequin-midi.webp",
    rating: 4.9,
    reviewCount: 124,
    description: "فستان ميدي مزين بالترتر بتصميم A-line وياقة مربعة. لإطلالات السهرة المميزة.",
  },
  {
    id: "wm-004",
    slug: "wtf-pearl-sandal",
    nameAr: "صندل مسطح مزين باللؤلؤ",
    nameEn: "Where's That From Eve Pearl Embellished Sandal",
    price: 134,
    originalPrice: 370,
    category: "women",
    brand: "Where's That From",
    brandAr: "وير از ذات فروم",
    brandSlug: "wheres-that-from",
    sizes: ["36", "37", "38", "39", "40", "41"],
    colors: [{ name: "روز جولد", hex: "#b76e79" }],
    image: "/voga/products/wtf-sandal.webp",
    rating: 4.5,
    reviewCount: 92,
    description: "صندل مسطح بتزيينات اللؤلؤ. خفيف ومريح للارتداء اليومي والمناسبات.",
  },
  {
    id: "wm-005",
    slug: "coast-maxi-embellished",
    nameAr: "فستان ماكسي بكسرات مزين بأحجار",
    nameEn: "Coast Fashion Embellished Maxi Dress with Godet Pleats",
    price: 811,
    originalPrice: 1352,
    category: "women",
    brand: "Coast Fashion",
    brandAr: "كوست فاشن",
    brandSlug: "coast-fashion",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "كحلي", hex: "#1a2942" }],
    image: "/voga/products/coast-maxi-embellished.webp",
    rating: 4.8,
    reviewCount: 41,
    description: "فستان ماكسي مزين بالأحجار الكريمة وكسرات جوديت. الأكثر مبيعًا في فئة فساتين السهرة.",
  },
  {
    id: "wm-006",
    slug: "plt-indigo-vest",
    nameAr: "فيست دينم باللون الأزرق",
    nameEn: "Prettylittlething Indigo Denim Vest",
    price: 132,
    originalPrice: 240,
    category: "women",
    brand: "PrettyLittleThing",
    brandAr: "بريتي ليتل ثينق",
    brandSlug: "prettylittlething",
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "أزرق دينم", hex: "#4a6fa5" }],
    image: "/voga/products/plt-indigo-vest.webp",
    rating: 4.3,
    reviewCount: 156,
    description: "فيست دينم بياقة دائرية وحزام مزموم. عصري ومثالي للإطلالات الكاجوال.",
  },
  {
    id: "wm-007",
    slug: "plt-taupe-maxi",
    nameAr: "فستان ماكسي مزموم",
    nameEn: "Prettylittlething Slinky Ruched Maxi Dress",
    price: 97,
    originalPrice: 277,
    category: "women",
    brand: "PrettyLittleThing",
    brandAr: "بريتي ليتل ثينق",
    brandSlug: "prettylittlething",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "نود", hex: "#d4b896" }],
    image: "/voga/products/plt-taupe-maxi.webp",
    rating: 4.4,
    reviewCount: 203,
    description: "فستان ماكسي بقماش سلينكي مزموم. يبرز القوام بأناقة وراحة.",
  },

  // ───── MEN (6 — real images from Voga PLP) ─────
  {
    id: "mn-001",
    slug: "boohooman-black-tee",
    nameAr: "تيشيرت بوهو مان أسود بأكمام متوسطة الطول",
    nameEn: "BoohooMAN Black Mid-Sleeve T-Shirt",
    price: 99,
    originalPrice: 159,
    category: "men",
    brand: "BoohooMAN",
    brandAr: "بوهو مان",
    brandSlug: "boohoo-man",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "أسود", hex: "#000" }],
    image: "/voga/products/boohooman-black-tee.webp",
    rating: 4.5,
    reviewCount: 287,
    description: "تيشيرت قطني بأكمام متوسطة بقصة عصرية. أساسي لخزانة كل رجل.",
  },
  {
    id: "mn-002",
    slug: "men-oversized-tee-black",
    nameAr: "تيشيرت بقصة عريضة - أسود",
    nameEn: "Oversized Cut T-Shirt - Black",
    price: 149,
    category: "men",
    brand: "Voga Essentials",
    brandAr: "فوغا إسنشيالز",
    brandSlug: "voga-essentials",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "أسود", hex: "#000" }, { name: "أبيض", hex: "#fff" }],
    image: "/voga/products/men-oversized-tee-black.webp",
    rating: 4.6,
    reviewCount: 112,
    description: "تيشيرت بقصة عريضة وخامة قطنية ناعمة. التريند الحالي للرجال.",
  },
  {
    id: "mn-003",
    slug: "men-wide-leg-sweatpants",
    nameAr: "بنطلون رياضي بأرجل عريضة",
    nameEn: "Wide Leg Sweatpants",
    price: 189,
    originalPrice: 259,
    category: "men",
    brand: "Voga Sport",
    brandAr: "فوغا سبورت",
    brandSlug: "voga-sport",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "أسود", hex: "#000" }, { name: "رمادي", hex: "#666" }],
    image: "/voga/products/men-wide-leg-sweatpants.webp",
    rating: 4.4,
    reviewCount: 198,
    description: "بنطلون رياضي بأرجل عريضة وقماش مريح. مثالي للأنشطة الرياضية والإطلالات الكاجوال.",
  },
  {
    id: "mn-004",
    slug: "men-printed-tee-beige",
    nameAr: "تيشيرت بتصميم واسع عريض بطبعة - بيج",
    nameEn: "Wide Cut Printed T-Shirt - Beige",
    price: 119,
    category: "men",
    brand: "Voga Essentials",
    brandAr: "فوغا إسنشيالز",
    brandSlug: "voga-essentials",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "بيج", hex: "#d4c5a0" }],
    image: "/voga/products/men-printed-tee-beige.webp",
    rating: 4.3,
    reviewCount: 76,
    description: "تيشيرت قطني بقصة واسعة وطبعة عصرية. لإطلالات الصيف المريحة.",
  },
  {
    id: "mn-005",
    slug: "men-camo-shorts",
    nameAr: "شورت فضفاض بطبعة مموهة",
    nameEn: "Relaxed Camouflage Shorts",
    price: 169,
    category: "men",
    brand: "Voga Sport",
    brandAr: "فوغا سبورت",
    brandSlug: "voga-sport",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "أسود", hex: "#000" }, { name: "أخضر زيتي", hex: "#3a4d2c" }],
    image: "/voga/products/men-camo-shorts.webp",
    rating: 4.5,
    reviewCount: 134,
    description: "شورت بقصة فضفاضة وطبعة كاموفلاج. مريح وعصري للصيف.",
  },
  {
    id: "mn-006",
    slug: "men-wide-pants-black",
    nameAr: "بنطلون رياضي بأرجل عريضة - أسود",
    nameEn: "Wide Leg Athletic Pants - Black",
    price: 199,
    category: "men",
    brand: "Voga Sport",
    brandAr: "فوغا سبورت",
    brandSlug: "voga-sport",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "أسود", hex: "#000" }],
    image: "/voga/products/men-wide-pants-black.webp",
    rating: 4.4,
    reviewCount: 167,
    description: "بنطلون رياضي بأرجل عريضة بخامة عالية الجودة. أنيق ومريح.",
  },

  // ───── KIDS (3 — gradient placeholders; PLPs not extracted this session) ─────
  {
    id: "kd-001",
    slug: "next-kids-tshirt",
    nameAr: "تيشيرت أطفال من نكست",
    nameEn: "NEXT Kids Cotton T-Shirt",
    price: 49,
    originalPrice: 79,
    category: "kids",
    brand: "NEXT",
    brandAr: "نكست",
    brandSlug: "next",
    sizes: ["3-4", "5-6", "7-8", "9-10", "11-12"],
    colors: [{ name: "أحمر", hex: "#dc2626" }, { name: "أصفر", hex: "#facc15" }, { name: "أخضر", hex: "#22c55e" }],
    emoji: "👕",
    bgGradient: "from-yellow-200 to-yellow-400",
    rating: 4.6,
    reviewCount: 521,
    description: "تيشيرت قطني ناعم بألوان زاهية. متين ومريح للأطفال.",
  },
  {
    id: "kd-002",
    slug: "river-island-kids-dress",
    nameAr: "فستان بنات بطبقات تول",
    nameEn: "River Island Girls Tulle Dress",
    price: 139,
    category: "kids",
    brand: "River Island",
    brandAr: "ريفر آيلاند",
    brandSlug: "river-island",
    sizes: ["3-4", "5-6", "7-8", "9-10"],
    colors: [{ name: "وردي", hex: "#f9a8d4" }],
    emoji: "👗",
    bgGradient: "from-pink-200 to-pink-500",
    rating: 4.7,
    reviewCount: 89,
    description: "فستان بنات بطبقات تول ناعمة. مثالي للمناسبات والحفلات.",
  },
  {
    id: "kd-003",
    slug: "kids-sneakers",
    nameAr: "حذاء رياضي للأطفال",
    nameEn: "Kids Lightweight Sneakers",
    price: 119,
    category: "kids",
    brand: "Voga Sport",
    brandAr: "فوغا سبورت",
    brandSlug: "voga-sport",
    sizes: ["28", "29", "30", "31", "32", "33", "34"],
    colors: [{ name: "أبيض", hex: "#fff" }, { name: "أزرق", hex: "#3b82f6" }],
    emoji: "👟",
    bgGradient: "from-cyan-200 to-cyan-500",
    rating: 4.5,
    reviewCount: 234,
    description: "حذاء رياضي خفيف وعملي للنشاطات اليومية والمدرسة.",
  },

  // ───── BEAUTY (3 — gradient placeholders) ─────
  {
    id: "by-001",
    slug: "luxury-perfume",
    nameAr: "عطر فاخر للسيدات",
    nameEn: "Luxury Eau de Parfum",
    price: 450,
    originalPrice: 590,
    category: "beauty",
    brand: "Kerastase",
    brandAr: "كيراستاس",
    brandSlug: "kerastase",
    sizes: ["50ml", "100ml"],
    colors: [{ name: "وردي عتيق", hex: "#d6abb1" }],
    emoji: "🌹",
    bgGradient: "from-rose-300 to-rose-600",
    rating: 4.9,
    reviewCount: 312,
    description: "عطر زهري شرقي بنفحات الورد والياسمين. مناسب لجميع المناسبات.",
  },
  {
    id: "by-002",
    slug: "matte-lipstick-set",
    nameAr: "مجموعة أحمر شفاه مات",
    nameEn: "Matte Lipstick Trio Set",
    price: 119,
    category: "beauty",
    brand: "Makeup Revolution",
    brandAr: "ميك أب ريفولوشن",
    brandSlug: "makeup-revolution",
    sizes: ["مجموعة"],
    colors: [{ name: "ألوان متعددة", hex: "#c2185b" }],
    emoji: "💄",
    bgGradient: "from-fuchsia-300 to-fuchsia-600",
    rating: 4.4,
    reviewCount: 187,
    description: "ثلاث درجات من أحمر الشفاه المات بثبات يدوم طويلاً.",
  },
  {
    id: "by-003",
    slug: "skincare-set",
    nameAr: "روتين العناية بالبشرة",
    nameEn: "Complete Skincare Routine Set",
    price: 380,
    originalPrice: 520,
    category: "beauty",
    brand: "Olaplex",
    brandAr: "أولابليكس",
    brandSlug: "olaplex",
    sizes: ["مجموعة"],
    colors: [{ name: "كريمي", hex: "#f5f5dc" }],
    emoji: "🧴",
    bgGradient: "from-emerald-100 to-emerald-300",
    rating: 4.7,
    reviewCount: 156,
    description: "روتين متكامل (غسول + تونر + سيروم + مرطب). للبشرة المختلطة والدهنية.",
  },

  // ───── HOME (4 — gradient placeholders) ─────
  {
    id: "hm-001",
    slug: "linen-bedding-set",
    nameAr: "طقم سرير من الكتان",
    nameEn: "Premium Linen Bedding Set",
    price: 620,
    originalPrice: 850,
    category: "home",
    brand: "Voga Home",
    brandAr: "فوغا هوم",
    brandSlug: "voga-home",
    sizes: ["مفرد", "نص مزدوج", "مزدوج", "كنج"],
    colors: [
      { name: "بيج", hex: "#e8dcc4" },
      { name: "رمادي", hex: "#a8a8a8" },
      { name: "أبيض", hex: "#fafafa" },
    ],
    emoji: "🛏️",
    bgGradient: "from-stone-100 to-stone-400",
    rating: 4.8,
    reviewCount: 92,
    description: "طقم سرير من الكتان الطبيعي يشمل مفرش + غطاء لحاف + كيسي مخدة.",
  },
  {
    id: "hm-002",
    slug: "scented-candle-set",
    nameAr: "شموع معطرة (طقم 3)",
    nameEn: "Set of 3 Scented Candles",
    price: 159,
    category: "home",
    brand: "Voga Home",
    brandAr: "فوغا هوم",
    brandSlug: "voga-home",
    sizes: ["طقم 3"],
    colors: [{ name: "كهرماني", hex: "#d4a574" }],
    emoji: "🕯️",
    bgGradient: "from-amber-100 to-amber-400",
    rating: 4.6,
    reviewCount: 234,
    description: "شموع طبيعية بثلاث روائح: ياسمين، خشب الصندل، فانيليا.",
  },
  {
    id: "hm-003",
    slug: "ceramic-vase-set",
    nameAr: "طقم مزهريات سيراميك",
    nameEn: "Ceramic Vase Trio",
    price: 289,
    category: "home",
    brand: "Voga Home",
    brandAr: "فوغا هوم",
    brandSlug: "voga-home",
    sizes: ["طقم 3"],
    colors: [{ name: "أبيض", hex: "#f5f5f5" }, { name: "تيراكوتا", hex: "#c47b51" }],
    emoji: "🏺",
    bgGradient: "from-orange-200 to-orange-400",
    rating: 4.7,
    reviewCount: 67,
    description: "ثلاث مزهريات سيراميك بأحجام مختلفة. تضيف لمسة عصرية لأي ركن.",
  },
  {
    id: "hm-004",
    slug: "throw-blanket",
    nameAr: "بطانية صوف ناعمة",
    nameEn: "Soft Wool Throw Blanket",
    price: 199,
    category: "home",
    brand: "Voga Home",
    brandAr: "فوغا هوم",
    brandSlug: "voga-home",
    sizes: ["130×170سم"],
    colors: [{ name: "كاميل", hex: "#a87b4e" }],
    emoji: "🛋️",
    bgGradient: "from-amber-200 to-amber-600",
    rating: 4.5,
    reviewCount: 178,
    description: "بطانية صوف ناعمة للأريكة أو السرير. دافئة وخفيفة الوزن.",
  },
];

export function productsByCategory(slug: Product["category"]): Product[] {
  return PRODUCTS.filter((p) => p.category === slug);
}

export function productBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function productById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function formatSAR(amount: number): string {
  return `${amount.toLocaleString("ar-SA")} ر.س`;
}
